### ISSUE TITLE
File changes not appearing to propagate correctly.

### ISSUE THREAD

**Issue by jSML4ThWwBID69YC** [moosefs/moosefs#374]
## Is this a BUG report, FEATURE request, or a QUESTION?

BUG report

## System information 

MooseFS v3.0.113 on all systems. 
FreeBSD 12.1 p5 or p6 on all systems. 
4x chunk servers. 
1x master
1x metadata
3x clients

Network: 2x 10GBe using LACP for each server. 

#### How much data is tracked by moosefs master (order of magnitude)?

 - All fs objects: 11578016
 - Total space: 76 TiB
 - Free space: 71 TiB
 - RAM used: 3.5 GiB
 - last metadata save duration: ~5.4s

## Describe the problem you observed.

Using the default mfscachemode of FBSDAUTO on FreeBSD 12.1p6 leads to temporary data corruption. Changes in files do not always show on other mfs mount points.

I believe this is somehow related to interaction with the FuseFS cache on FreeBSD. This issue was discovered as part of testing for issue  https://github.com/moosefs/moosefs/issues/362

This issue started occurring with 3.0.113. I don't recall it happening in earlier versions. 

#### Can you reproduce it? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes. 

1: Edit files on one mfs mount and check on another mfs mount. The files do not always show the changes. For example, create a text file and add content. Check it on a second mfs mount and add additional content. The first mount won't show the changes some of the time. The mfsfileinfo tool shows that the files are the same, even though directly viewing the file shows differences. 

I've also seen that sometimes the files do appear to change on mfs, but the new files are not picked up by software accessing it. For example, editing a .css file with code changes. Accessing that file through Nginx shows the old version even when mfs shows the correct version. I've verified it's not a Nginx cache, or related item. 

Unmounting and remounting the mfs export shows the correct files with the changes. I suspect the issue is related to FuseFS caching. 

#### Include any warning/errors/backtraces from the system logs

This is the only error that seems related. It happens a lot on 3.0.113 though I can't pin it to any specific operation. 

```
kernel: fuse_vnop_lookup: WB cache incoherent on /path/to/mfs/mount.
```

**Comment by chogata** [comment]
I am able to replicate this, we are investigating if the issue is with MooseFS, FreeBSD or both.

**Comment by chogata** [comment]
Okay, so the issue is both with MooseFS and FreeBSD. We corrected our part, so it will work in the future. A patch will be posted soon and included in next release.

**Comment by jSML4ThWwBID69YC** [comment]
The above patches seem to have resolved this issue. I've been running them for about eight hours without the issue happening again. 

I still see the ```kernel: fuse_vnop_lookup: WB cache incoherent on /path/to/mfs/mount``` message occasionally.

**Comment by chogata** [comment]
There is a problem with implementation of `fuse_lowlevel_notify_inval_inode` in FreeBSD kernel. This message might or might not have something to do with it. We will report this to FreeBSD - I will post a link, as usual :)

**Comment by jSML4ThWwBID69YC** [comment]
@chogata 

I've checked again this morning and the ```kernel: fuse_vnop_lookup: WB cache incoherent on /path/to/mfs/mount``` only happens when Nginx is running. Out of eighteen client mount points, the two running Nginx show the error. Seems like Nginx is doing something to trigger it that other software is not. Sendfile issue maybe?
