### ISSUE TITLE
ETIMEDOUT (Operation timed out)

### ISSUE THREAD

**Issue by Damien9527** [moosefs/moosefs#47]
my mfsmaster  version is 3.0.84 and my chunkserver  version is 3.0.85 .

recently ,some error appear:

Mar 15 03:00:29 localhost mfschunkserver[3545]: connect to 10.39.54.219:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 15 03:00:31 localhost mfschunkserver[3545]: connect to 10.39.54.219:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 15 03:00:33 localhost mfschunkserver[3545]: connect to 10.39.54.218:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 15 03:00:36 localhost mfschunkserver[3545]: connect to 10.39.54.219:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 15 03:00:38 localhost mfschunkserver[3545]: connect to 10.39.54.220:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 15 03:00:44 localhost mfschunkserver[3545]: connect to 10.39.54.219:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 15 03:00:51 localhost mfschunkserver[3545]: connect to 10.39.54.219:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 15 03:00:52 localhost mfschunkserver[3545]: connect to 10.39.54.219:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 15 03:00:53 localhost mfschunkserver[3545]: connect to 10.39.54.217:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 15 03:00:58 localhost mfschunkserver[3545]: connect to 10.39.54.218:9432 failed, error: ETIMEDOUT (Operation timed out)

and in the mfscgi ,   max operations in queue   at the time  03--04 . is very high .   sure that time the 
concurrent  write operation is  high ，but the traffice in only 70% of the network card.   

and also ,the cpu wait io ,load  in that time is very low .    

any idea about this ?  should i  make the queue  size bigger ?

**Comment by xandrus** [comment]
Hi.
I would like to know what you mean "max operations in queue".
Is is load column on servers tab?
How many write operations per minute you have during  ETIMEDOUT error?

We would like to know little more details about your current configuration. Number of chunkservers and hard disks.

**Comment by marcin-github** [comment]
I would like to advise to upgrade mfs-master to 3.0.88

**Comment by Damien9527** [comment]
@xandrus  
    is  load column on server chats tab   like :     http://domain/mfs.cgi?sections=CC&CCdata=load 

Mar 16 03:00:44 localhost mfschunkserver[3545]: connect to 10.39.54.217:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 16 03:00:46 localhost mfschunkserver[3545]: **workers: 80+**
Mar 16 03:00:49 localhost mfschunkserver[3545]: connect to 10.39.54.217:9432 failed, error: ETIMEDOUT (Operation timed out)

     the write operations  in 03 clock , I collected is more the  1000+  , write  many small file . 

   I don't change any  configuration .  here I  have 5 chunkservers .  each chunkserver have 2 bonding network cards (2000Mb/s).    and  12 * 4T  disks  in each chunkserver. used  Raid5 .

**Comment by xandrus** [comment]
OK.
Which bond mode you are using?
Please check your network - dropped packages and errors on NIC and switch.

By the way.
RAID as MooseFS chunkserver disk is rather bad idea. Performance is much better when you use just JBOD a specially when we are talking about many parallel operations.

**Comment by Damien9527** [comment]
Hi  @xandrus   ,
   My NIC configuration :  options bond0 mode=balance-rr use_carrier=1 miimon=1
    Yes , my NIC has  many  dropped packages  in  all of my chunkserver .

   bond0     Link encap:Ethernet  HWaddr 6C:92:BF:37:A9:88
          inet addr:10.39.54.216  Bcast:10.39.54.255  Mask:255.255.255.0
          inet6 addr: fe80::6e92:bfff:fe37:a988/64 Scope:Link
          UP BROADCAST RUNNING MASTER MULTICAST  MTU:1500  Metric:1
          RX packets:10825123543 errors:0 **dropped:5816** **overruns:5816** frame:0
          TX packets:10012278555 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
           RX bytes:9609689160943 (8.7 TiB)  TX bytes:9162350076392 (8.3 TiB)
   
 
    I have already open the Multi queue network card function in one of my chunkserver ,but it seems  not effective .

   the message here:

Mar 17 03:00:55 localhost mfschunkserver[1353]: connect to 10.39.54.219:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 17 03:01:01 localhost mfschunkserver[1353]: connect to 10.39.54.218:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 17 03:01:06 localhost mfschunkserver[1353]: connect to 10.39.54.220:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 17 03:01:08 localhost mfschunkserver[1353]: connect to 10.39.54.217:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 17 03:01:12 localhost mfschunkserver[1353]: connect to 10.39.54.220:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 17 03:01:18 localhost mfschunkserver[1353]: workers: 60-
Mar 17 03:01:20 localhost mfschunkserver[1353]: workers: 50-
Mar 17 03:01:31 localhost mfschunkserver[1353]: workers: 40-
Mar 17 03:03:04 localhost mfschunkserver[1353]: workers: 50+
Mar 17 03:03:05 localhost mfschunkserver[1353]: connect to 10.39.54.218:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 17 03:03:08 localhost mfschunkserver[1353]: connect to 10.39.54.218:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 17 03:03:08 localhost mfschunkserver[1353]: connect to 10.39.54.218:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 17 03:03:08 localhost mfschunkserver[1353]: workers: 60+
Mar 17 03:03:12 localhost mfschunkserver[1353]: connect to 10.39.54.217:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 17 03:03:28 localhost mfschunkserver[1353]: connect to 10.39.54.220:9432 failed, error: ETIMEDOUT (Operation timed out)
Mar 17 03:03:30 localhost mfschunkserver[1353]: connect to 10.39.54.220:9432 failed, error: ETIMEDOUT (Operation timed out)

 
nearly that time:
 03/17/2017 03:00:56 
 chunkserver1:
Total: 205 (kernel 500)
TCP:   5123 (estab 100, closed 5016, orphaned 1, synrecv 0, timewait 5016/0), ports 5471

chunkserver2:

Total: 259 (kernel 514)
TCP:   5058 (estab 136, closed 4911, orphaned 0, synrecv 0, timewait 4909/0), ports 5083

chunkserver3:
Total: 223 (kernel 508)
TCP:   4419 (estab 106, closed 4303, orphaned 1, synrecv 0, timewait 4302/0), ports 4454

chunkserver4:
Total: 226 (kernel 469)
TCP:   2870 (estab 113, closed 2750, orphaned 0, synrecv 0, timewait 2749/0), ports 3211

chunkserver5:
TCP:   2870 (estab 113, closed 2750, orphaned 0, synrecv 0, timewait 2749/0), ports 3211

**Comment by Damien9527** [comment]
@xandrus    i add  another two chunks server ,but the etimeout status  still  like before  .  

  I  don't know  what this error message means .   Could you tell me that ?

**Comment by xandrus** [comment]
Hi,
sorry I miss this mail.
It means that this specific operation spend too much time on execution.
It's nothing unusual in LAN, but in your case it's something different.

I suspect that your master server has disabled overcommit memory option in kernel.
`echo 1 > / proc /sys/vm/ overcommit_memory`

All of this happens during full hour, when MooseFS master dumps metadata.

Please read about this aspect in our documentation on page 47.
https://moosefs.com/Content/Downloads/moosefs-3-0-users-manual.pdf

**Comment by Damien9527** [comment]
Hi
    follow your advise.I have change the  overcommit_memory  as you say.    
    I do it like this :

echo "vm.overcommit_memory=1”>>/etc/sysctl.conf
sysctl -p

[root@mfsmaster1 ~]# cat /proc/sys/vm/overcommit_memory
1

   

But it didn't seem to work ：
I change  it  at 00:10，and the error  still  exist.   but I don't restart or reload the master process ,should I do that ?

May 20 01:00:07 localhost mfschunkserver[26420]: masterconn: connection timed out
May 20 01:00:10 localhost mfschunkserver[26420]: connecting ...
May 20 01:00:10 localhost mfschunkserver[26420]: connected to Master
May 20 02:37:31 localhost mfschunkserver[26420]: connect to 10.39.3.30:9432 failed, error: ETIMEDOUT (Operation timed out)
May 20 02:40:24 localhost mfschunkserver[26420]: connect to 10.39.54.218:9432 failed, error: ETIMEDOUT (Operation timed out)
May 20 02:56:28 localhost mfschunkserver[26420]: connect to 10.39.54.218:9432 failed, error: ETIMEDOUT (Operation timed out)
May 20 03:03:02 localhost mfschunkserver[26420]: connect to 10.39.54.218:9432 failed, error: ETIMEDOUT (Operation timed out)
May 20 03:34:36 localhost mfschunkserver[26420]: connect to 10.39.3.30:9432 failed, error: ETIMEDOUT (Operation timed out)
May 20 03:47:02 localhost mfschunkserver[26420]: connect to 10.39.54.215:9432 failed, error: ETIMEDOUT (Operation timed out)
May 20 04:23:29 localhost mfschunkserver[26420]: connect to 10.39.3.30:9432 failed, error: ETIMEDOUT (Operation timed out)
May 20 04:23:55 localhost mfschunkserver[26420]: connect to 10.39.3.30:9432 failed, error: ETIMEDOUT (Operation timed out)
May 20 04:54:36 localhost mfschunkserver[26420]: connect to 10.39.54.215:9432 failed, error: ETIMEDOUT (Operation timed out)
May 20 05:13:04 localhost mfschunkserver[26420]: connect to 10.39.3.30:9432 failed, error: ETIMEDOUT (Operation timed out)
May 20 05:16:12 localhost mfschunkserver[26420]: connect to 10.39.3.30:9432 failed, error: ETIMEDOUT (Operation timed out)
May 20 05:22:36 localhost mfschunkserver[26420]: connect to 10.39.3.30:9432 failed, error: ETIMEDOUT (Operation timed out)
May 20 05:31:46 localhost mfschunkserver[26420]: connect to 10.39.3.30:9432 failed, error: ETIMEDOUT (Operation timed out)
May 20 05:36:17 localhost mfschunkserver[26420]: connect to 10.39.3.30:9432 failed, error: ETIMEDOUT (Operation timed out)
May 20 05:36:17 localhost mfschunkserver[26420]: connect to 10.39.3.30:9432 failed, error: ETIMEDOUT (Operation timed out)
May 20 05:38:33 localhost mfschunkserver[26420]: connect to 10.39.54.219:9432 failed, error: ETIMEDOUT (Operation timed out)
May 20 06:34:24 localhost mfschunkserver[26420]: connect to 10.39.54.220:9432 failed, error: ETIMEDOUT (Operation timed out)

**Comment by xandrus** [comment]
You don't have to restart MooseFS master process.
Can you send us logs from your MooseFS Master server?

Right now it's look again like network problems. 
Personally I believe that in bond mode 80%  network usage is equal to 100%.

Please try to adjust MATOCS_TIMEOUT settings in mfsmaster.cfg. Reload configuration and check result.

`MATOCS_TIMEOUT = 30`

**Comment by Damien9527** [comment]
the master log :

``May 22 00:00:07 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 5.622
May 22 00:34:39 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 01:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 01:00:11 mfsmaster1 mfsmaster[7027]: child finished
May 22 01:00:11 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 10.168
May 22 01:29:24 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 02:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 02:00:07 mfsmaster1 mfsmaster[7027]: child finished
May 22 02:00:07 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 6.226
May 22 02:24:05 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 03:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 03:00:07 mfsmaster1 mfsmaster[7027]: child finished
May 22 03:00:07 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 6.370
May 22 03:18:48 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 04:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 04:00:10 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.3.30 / port: 9432, usedspace: 6829617876992 (6360.58 GiB), totalspace: 20718595727360 (19295.70 GiB)
May 22 04:00:10 mfsmaster1 mfsmaster[7027]: child finished
May 22 04:00:10 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 8.821
May 22 04:00:10 mfsmaster1 mfsmaster[7027]: connection with client(ip:10.39.5.117) has been closed by peer
May 22 04:00:10 mfsmaster1 mfsmaster[7027]: connection with client(ip:10.39.4.103) has been closed by peer
May 22 04:00:10 mfsmaster1 mfsmaster[7027]: connection with client(ip:10.39.3.89) has been closed by peer
May 22 04:00:10 mfsmaster1 mfsmaster[7027]: connection with client(ip:10.39.4.110) has been closed by peer
May 22 04:00:10 mfsmaster1 mfsmaster[7027]: connection with client(ip:10.39.5.129) has been closed by peer
May 22 04:00:10 mfsmaster1 mfsmaster[7027]: connection with client(ip:10.39.5.225) has been closed by peer
May 22 04:00:13 mfsmaster1 mfsmaster[7027]: csdb: found cs using ip:port and csid (10.39.3.30:9432,1)
May 22 04:00:13 mfsmaster1 mfsmaster[7027]: chunkserver register begin (packet version: 6) - ip: 10.39.3.30 / port: 9432, usedspace: 6829657718784 (6360.61 GiB), totalspace: 20718595727360 (19295.70 GiB)
May 22 04:00:14 mfsmaster1 mfsmaster[7027]: server ip: 10.39.3.30 / port: 9432 has been fully removed from data structures
May 22 04:00:15 mfsmaster1 mfsmaster[7027]: chunkserver register end (packet version: 6) - ip: 10.39.3.30 / port: 9432
May 22 04:23:34 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 05:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 05:00:07 mfsmaster1 mfsmaster[7027]: child finished
May 22 05:00:07 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 5.694
May 22 05:18:16 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 05:42:57 mfsmaster1 mfsmaster[7027]: (10.39.54.215:9432 -> 10.39.54.219:9432) chunk: 00000000021BCF09 replication status: Wrong chunk version
May 22 06:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 06:00:06 mfsmaster1 mfsmaster[7027]: child finished
May 22 06:00:06 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 5.505
May 22 06:12:57 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 07:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 07:00:06 mfsmaster1 mfsmaster[7027]: child finished
May 22 07:00:06 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 5.237
May 22 07:07:39 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 08:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 08:00:07 mfsmaster1 mfsmaster[7027]: child finished
May 22 08:00:07 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 5.743
May 22 08:02:20 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 08:22:47 mfsmaster1 mfsmaster[7027]: (10.39.54.215:9432 -> 10.39.54.218:9432) chunk: 00000000021BD009 replication status: Wrong chunk version
May 22 08:56:57 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 09:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 09:00:07 mfsmaster1 mfsmaster[7027]: child finished
May 22 09:00:07 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 6.074
May 22 09:51:39 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 10:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 10:00:17 mfsmaster1 mfsmaster[7027]: child finished
May 22 10:00:17 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 15.280
May 22 10:46:20 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 11:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 11:00:07 mfsmaster1 mfsmaster[7027]: child finished
May 22 11:00:07 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 5.602
May 22 11:18:43 mfsmaster1 mfsmaster[7027]: connection with CS(10.39.54.215) has been closed by peer
May 22 11:18:43 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.54.215 / port: 9432, usedspace: 888025899008 (827.04 GiB), totalspace: 2477785313280 (2307.62 GiB)
May 22 11:18:45 mfsmaster1 mfsmaster[7027]: csdb: found cs using ip:port and csid (10.39.54.215:9432,2)
May 22 11:18:45 mfsmaster1 mfsmaster[7027]: chunkserver register begin (packet version: 6) - ip: 10.39.54.215 / port: 9432, usedspace: 100943589376 (94.01 GiB), totalspace: 279768502272 (260.55 GiB)
May 22 11:18:45 mfsmaster1 mfsmaster[7027]: chunkserver register end (packet version: 6) - ip: 10.39.54.215 / port: 9432
May 22 11:18:47 mfsmaster1 mfsmaster[7027]: server ip: 10.39.54.215 / port: 9432 has been fully removed from data structures
May 22 11:22:54 mfsmaster1 mfsmaster[7027]: chunk 00000000021F6391_00000001: chunk hasn't been deleted since previous loop - retry
May 22 11:22:54 mfsmaster1 mfsmaster[7027]: chunk 00000000021F6391_00000001: chunk hasn't been deleted since previous loop - retry
May 22 11:22:54 mfsmaster1 mfsmaster[7027]: (10.39.3.30:9432) chunk: 00000000021F6391 deletion status: No such chunk
May 22 11:22:54 mfsmaster1 mfsmaster[7027]: (10.39.54.216:9432) chunk: 00000000021F6391 deletion status: No such chunk
May 22 11:23:11 mfsmaster1 mfsmaster[7027]: (10.39.3.30:9432 -> 10.39.3.31:9432) chunk: 00000000021D4F68 replication status: Disconnected
May 22 11:28:18 mfsmaster1 mfsmaster[7027]: (10.39.3.31:9432) chunk: 00000000021D4F68 deletion status: No such chunk
May 22 11:44:36 mfsmaster1 mfsmaster[7027]: chunk 00000000021FEA29_00000001: chunk hasn't been deleted since previous loop - retry
May 22 11:44:36 mfsmaster1 mfsmaster[7027]: chunk 00000000021FEA29_00000001: chunk hasn't been deleted since previous loop - retry
May 22 11:44:36 mfsmaster1 mfsmaster[7027]: (10.39.3.30:9432) chunk: 00000000021FEA29 deletion status: No such chunk
May 22 11:44:36 mfsmaster1 mfsmaster[7027]: (10.39.54.220:9432) chunk: 00000000021FEA29 deletion status: No such chunk
May 22 11:51:00 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 12:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 12:00:07 mfsmaster1 mfsmaster[7027]: child finished
May 22 12:00:07 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 5.425
May 22 12:45:42 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 12:55:03 mfsmaster1 mfsmaster[7027]: connection with CS(10.39.54.215) has been closed by peer
May 22 12:55:03 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.54.215 / port: 9432, usedspace: 101781192704 (94.79 GiB), totalspace: 279768502272 (260.55 GiB)
May 22 12:55:04 mfsmaster1 mfsmaster[7027]: csdb: found cs using ip:port and csid (10.39.54.215:9432,2)
May 22 12:55:04 mfsmaster1 mfsmaster[7027]: chunkserver register begin (packet version: 6) - ip: 10.39.54.215 / port: 9432, usedspace: 0 (0.00 GiB), totalspace: 0 (0.00 GiB)
May 22 12:55:04 mfsmaster1 mfsmaster[7027]: chunkserver register end (packet version: 6) - ip: 10.39.54.215 / port: 9432
May 22 12:55:06 mfsmaster1 mfsmaster[7027]: server ip: 10.39.54.215 / port: 9432 has been fully removed from data structures
May 22 12:56:21 mfsmaster1 mfsmaster[7027]: chunkserver graceful disconnection (packet version: 6) - ip: 10.39.54.215 / port: 9432
May 22 12:56:21 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.54.215 / port: 9432, usedspace: 0 (0.00 GiB), totalspace: 0 (0.00 GiB)
May 22 12:56:24 mfsmaster1 mfsmaster[7027]: server ip: 10.39.54.215 / port: 9432 has been fully removed from data structures
May 22 13:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 13:00:10 mfsmaster1 mfsmaster[7027]: child finished
May 22 13:00:10 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 9.415
May 22 13:51:38 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 14:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 14:00:10 mfsmaster1 mfsmaster[7027]: child finished
May 22 14:00:10 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 9.890
May 22 14:24:20 mfsmaster1 mfsmaster[7027]: remove session: 152
May 22 14:46:05 mfsmaster1 mfsmaster[7027]: created new sessionid:196
May 22 14:46:18 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 15:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 15:00:10 mfsmaster1 mfsmaster[7027]: child finished
May 22 15:00:10 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 8.879
May 22 15:07:27 mfsmaster1 mfsmaster[7027]: created new sessionid:197
May 22 15:07:30 mfsmaster1 mfsmaster[7027]: remove session: 196
May 22 15:26:09 mfsmaster1 mfsmaster[7027]: created new sessionid:198
May 22 15:26:10 mfsmaster1 mfsmaster[7027]: remove session: 197
May 22 15:41:02 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 16:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 16:00:08 mfsmaster1 mfsmaster[7027]: child finished
May 22 16:00:08 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 7.842
May 22 16:35:43 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 17:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 17:00:07 mfsmaster1 mfsmaster[7027]: child finished
May 22 17:00:07 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 6.006
May 22 17:30:25 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 17:45:54 mfsmaster1 heartbeat: [10830]: info: Daily informational memory statistics
May 22 17:45:54 mfsmaster1 heartbeat: [10830]: info: MSG stats: 8/13997937 ms age 0 [pid10830/MST_CONTROL]
May 22 17:45:54 mfsmaster1 heartbeat: [10830]: info: cl_malloc stats: 598/443733965  89992/44977 [pid10830/MST_CONTROL]
May 22 17:45:54 mfsmaster1 heartbeat: [10830]: info: RealMalloc stats: 122368 total malloc bytes. pid [10830/MST_CONTROL]
May 22 17:45:54 mfsmaster1 heartbeat: [10830]: info: Current arena value: 0
May 22 17:45:54 mfsmaster1 heartbeat: [10830]: info: MSG stats: 0/1 ms age 7775990550 [pid10833/HBFIFO]
May 22 17:45:54 mfsmaster1 heartbeat: [10830]: info: cl_malloc stats: 303/364  42596/21432 [pid10833/HBFIFO]
May 22 17:45:54 mfsmaster1 heartbeat: [10830]: info: RealMalloc stats: 45668 total malloc bytes. pid [10833/HBFIFO]
May 22 17:45:54 mfsmaster1 heartbeat: [10830]: info: Current arena value: 0
May 22 17:45:54 mfsmaster1 heartbeat: [10830]: info: MSG stats: 0/0 ms age 71841302860 [pid10834/HBWRITE]
May 22 17:45:54 mfsmaster1 heartbeat: [10830]: info: cl_malloc stats: 319/4895079  45476/23304 [pid10834/HBWRITE]
May 22 17:45:54 mfsmaster1 heartbeat: [10830]: info: RealMalloc stats: 64364 total malloc bytes. pid [10834/HBWRITE]
May 22 17:45:54 mfsmaster1 heartbeat: [10830]: info: Current arena value: 0
May 22 17:45:54 mfsmaster1 heartbeat: [10830]: info: MSG stats: 0/0 ms age 71841302860 [pid10835/HBREAD]
May 22 17:45:54 mfsmaster1 heartbeat: [10830]: info: cl_malloc stats: 323/18664819  45844/23428 [pid10835/HBREAD]
May 22 17:45:54 mfsmaster1 heartbeat: [10830]: info: RealMalloc stats: 47812 total malloc bytes. pid [10835/HBREAD]
May 22 17:45:54 mfsmaster1 heartbeat: [10830]: info: Current arena value: 0
May 22 17:45:54 mfsmaster1 heartbeat: [10830]: info: These are nothing to worry about.
May 22 18:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 18:00:08 mfsmaster1 mfsmaster[7027]: child finished
May 22 18:00:08 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 6.769
May 22 18:25:06 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 19:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 19:00:07 mfsmaster1 mfsmaster[7027]: child finished
May 22 19:00:07 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 6.398
May 22 19:19:49 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 20:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 20:00:07 mfsmaster1 mfsmaster[7027]: child finished
May 22 20:00:07 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 6.468
May 22 20:14:31 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 21:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 21:00:08 mfsmaster1 mfsmaster[7027]: child finished
May 22 21:00:08 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 7.109
May 22 21:09:12 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 22:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 22:00:09 mfsmaster1 mfsmaster[7027]: child finished
May 22 22:00:09 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 7.961
May 22 22:03:53 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 22:58:30 mfsmaster1 mfsmaster[7027]: structure check loop
May 22 23:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 22 23:00:08 mfsmaster1 mfsmaster[7027]: child finished
May 22 23:00:08 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 7.525
May 22 23:53:13 mfsmaster1 mfsmaster[7027]: structure check loop
May 23 00:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 23 00:00:09 mfsmaster1 mfsmaster[7027]: child finished
May 23 00:00:09 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 8.164
May 23 00:39:53 mfsmaster1 mfsmaster[7027]: connection with client(ip:10.39.3.117) has been closed by peer
May 23 00:47:55 mfsmaster1 mfsmaster[7027]: structure check loop
May 23 01:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 23 01:00:11 mfsmaster1 mfsmaster[7027]: child finished
May 23 01:00:11 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 10.488
May 23 01:42:36 mfsmaster1 mfsmaster[7027]: structure check loop
May 23 02:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 23 02:00:06 mfsmaster1 mfsmaster[7027]: child finished
May 23 02:00:06 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 5.683
May 23 02:37:17 mfsmaster1 mfsmaster[7027]: structure check loop
May 23 03:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 23 03:00:06 mfsmaster1 mfsmaster[7027]: child finished
May 23 03:00:06 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 5.556
May 23 03:27:08 mfsmaster1 mfsmaster[7027]: (10.39.3.30:9432 -> 10.39.54.218:9432) chunk: 000000000223F8B0 replication status: Wrong chunk version
May 23 03:27:26 mfsmaster1 mfsmaster[7027]: connection with client(ip:10.39.3.155) has been closed by peer
May 23 03:31:58 mfsmaster1 mfsmaster[7027]: structure check loop
May 23 04:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 23 04:00:09 mfsmaster1 mfsmaster[7027]: child finished
May 23 04:00:09 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 8.079
May 23 04:26:42 mfsmaster1 mfsmaster[7027]: structure check loop
May 23 05:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 23 05:00:06 mfsmaster1 mfsmaster[7027]: child finished
May 23 05:00:06 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 5.622
May 23 05:21:24 mfsmaster1 mfsmaster[7027]: structure check loop
May 23 06:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 23 06:00:08 mfsmaster1 mfsmaster[7027]: child finished
May 23 06:00:08 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 6.537
May 23 06:16:06 mfsmaster1 mfsmaster[7027]: structure check loop
May 23 07:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 23 07:00:07 mfsmaster1 mfsmaster[7027]: child finished
May 23 07:00:07 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 6.296
May 23 07:10:47 mfsmaster1 mfsmaster[7027]: structure check loop
May 23 08:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 23 08:00:10 mfsmaster1 mfsmaster[7027]: child finished
May 23 08:00:10 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 8.984
May 23 08:05:30 mfsmaster1 mfsmaster[7027]: structure check loop
May 23 09:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 23 09:00:07 mfsmaster1 mfsmaster[7027]: child finished
May 23 09:00:07 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 5.853
May 23 09:00:10 mfsmaster1 mfsmaster[7027]: structure check loop
May 23 09:54:20 mfsmaster1 mfsmaster[7027]: connection with CS(10.39.54.216) has been closed by peer
May 23 09:54:20 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.54.216 / port: 9432, usedspace: 13072417267712 (12174.64 GiB), totalspace: 35651799744512 (33203.33 GiB)
May 23 09:54:24 mfsmaster1 mfsmaster[7027]: csdb: found cs using ip:port and csid (10.39.54.216:9432,7)
May 23 09:54:24 mfsmaster1 mfsmaster[7027]: chunkserver register begin (packet version: 6) - ip: 10.39.54.216 / port: 9432, usedspace: 13072425738240 (12174.65 GiB), totalspace: 35651799744512 (33203.33 GiB)
May 23 09:54:24 mfsmaster1 mfsmaster[7027]: server ip: 10.39.54.216 / port: 9432 has been fully removed from data structures
May 23 09:54:26 mfsmaster1 mfsmaster[7027]: chunkserver register end (packet version: 6) - ip: 10.39.54.216 / port: 9432
May 23 09:55:17 mfsmaster1 mfsmaster[7027]: connection with CS(10.39.54.217) has been closed by peer
May 23 09:55:17 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.54.217 / port: 9432, usedspace: 13071516307456 (12173.80 GiB), totalspace: 35651799744512 (33203.33 GiB)
May 23 09:55:18 mfsmaster1 mfsmaster[7027]: csdb: found cs using ip:port and csid (10.39.54.217:9432,4)
May 23 09:55:18 mfsmaster1 mfsmaster[7027]: chunkserver register begin (packet version: 6) - ip: 10.39.54.217 / port: 9432, usedspace: 13071523708928 (12173.81 GiB), totalspace: 35651799744512 (33203.33 GiB)
May 23 09:55:21 mfsmaster1 mfsmaster[7027]: server ip: 10.39.54.217 / port: 9432 has been fully removed from data structures
May 23 09:55:22 mfsmaster1 mfsmaster[7027]: chunkserver register end (packet version: 6) - ip: 10.39.54.217 / port: 9432
May 23 09:56:54 mfsmaster1 mfsmaster[7027]: connection with CS(10.39.54.218) has been closed by peer
May 23 09:56:54 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.54.218 / port: 9432, usedspace: 13071045193728 (12173.36 GiB), totalspace: 35651799744512 (33203.33 GiB)
May 23 09:56:58 mfsmaster1 mfsmaster[7027]: csdb: found cs using ip:port and csid (10.39.54.218:9432,8)
May 23 09:56:58 mfsmaster1 mfsmaster[7027]: chunkserver register begin (packet version: 6) - ip: 10.39.54.218 / port: 9432, usedspace: 13071049613312 (12173.36 GiB), totalspace: 35651799744512 (33203.33 GiB)
May 23 09:56:59 mfsmaster1 mfsmaster[7027]: server ip: 10.39.54.218 / port: 9432 has been fully removed from data structures
May 23 09:57:01 mfsmaster1 mfsmaster[7027]: chunkserver register end (packet version: 6) - ip: 10.39.54.218 / port: 9432
May 23 09:58:06 mfsmaster1 mfsmaster[7027]: connection with CS(10.39.54.219) has been closed by peer
May 23 09:58:06 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.54.219 / port: 9432, usedspace: 13069450936320 (12171.87 GiB), totalspace: 35651799744512 (33203.33 GiB)
May 23 09:58:09 mfsmaster1 mfsmaster[7027]: csdb: found cs using ip:port and csid (10.39.54.219:9432,5)
May 23 09:58:09 mfsmaster1 mfsmaster[7027]: chunkserver register begin (packet version: 6) - ip: 10.39.54.219 / port: 9432, usedspace: 13069453008896 (12171.88 GiB), totalspace: 35651799744512 (33203.33 GiB)
May 23 09:58:11 mfsmaster1 mfsmaster[7027]: server ip: 10.39.54.219 / port: 9432 has been fully removed from data structures
May 23 09:58:12 mfsmaster1 mfsmaster[7027]: chunkserver register end (packet version: 6) - ip: 10.39.54.219 / port: 9432
May 23 09:58:55 mfsmaster1 mfsmaster[7027]: connection with CS(10.39.54.220) has been closed by peer
May 23 09:58:55 mfsmaster1 mfsmaster[7027]: chunkserver disconnected - ip: 10.39.54.220 / port: 9432, usedspace: 13167119306752 (12262.84 GiB), totalspace: 35651796955136 (33203.32 GiB)
May 23 09:58:58 mfsmaster1 mfsmaster[7027]: csdb: found cs using ip:port and csid (10.39.54.220:9432,6)
May 23 09:58:58 mfsmaster1 mfsmaster[7027]: chunkserver register begin (packet version: 6) - ip: 10.39.54.220 / port: 9432, usedspace: 13167121215488 (12262.84 GiB), totalspace: 35651796955136 (33203.32 GiB)
May 23 09:59:00 mfsmaster1 mfsmaster[7027]: server ip: 10.39.54.220 / port: 9432 has been fully removed from data structures
May 23 09:59:01 mfsmaster1 mfsmaster[7027]: chunkserver register end (packet version: 6) - ip: 10.39.54.220 / port: 9432
May 23 10:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 23 10:00:07 mfsmaster1 mfsmaster[7027]: child finished
May 23 10:00:07 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 5.798
May 23 10:09:22 mfsmaster1 mfsmaster[7027]: structure check loop
May 23 11:00:00 mfsmaster1 mfsmaster[7027]: no metaloggers connected !!!
May 23 11:00:07 mfsmaster1 mfsmaster[7027]: child finished
May 23 11:00:07 mfsmaster1 mfsmaster[7027]: store process has finished - store time: 5.958
May 23 11:04:05 mfsmaster1 mfsmaster[7027]: structure check loop
May 23 11:05:30 mfsmaster1 mfsmaster[7027]: created new sessionid:




we have put a lot of svn project on mfs,  should this be the reason that cause the ETIMEOUT ?

**Comment by xandrus** [comment]
Hi.
Svn project is not a problem.
Basically we do not advise to use higher chunkserevr version and client version than MooseFS master version.
Please try to update your cluster to latest 3.0.92 version.

I have another question connected with MooseFS master.
Is it virtual machine or hardware?
Do you have enough RAM for metadata + fork operation?

**Comment by Damien9527** [comment]
all the server is hardware .
the information below:

[root@mfsmaster1 data]# ls
changelog.0.mfs   changelog.15.mfs  changelog.20.mfs  changelog.26.mfs  changelog.31.mfs  changelog.37.mfs  changelog.42.mfs  changelog.48.mfs  changelog.7.mfs
changelog.10.mfs  changelog.16.mfs  changelog.21.mfs  changelog.27.mfs  changelog.32.mfs  changelog.38.mfs  changelog.43.mfs  changelog.49.mfs  changelog.8.mfs
changelog.11.mfs  changelog.17.mfs  changelog.22.mfs  changelog.28.mfs  changelog.33.mfs  changelog.39.mfs  changelog.44.mfs  changelog.4.mfs   changelog.9.mfs
changelog.12.mfs  changelog.18.mfs  changelog.23.mfs  changelog.29.mfs  changelog.34.mfs  changelog.3.mfs   changelog.45.mfs  changelog.50.mfs  metadata.mfs.back
changelog.13.mfs  changelog.19.mfs  changelog.24.mfs  changelog.2.mfs   changelog.35.mfs  changelog.40.mfs  changelog.46.mfs  changelog.5.mfs   metadata.mfs.back.1
changelog.14.mfs  changelog.1.mfs   changelog.25.mfs  changelog.30.mfs  changelog.36.mfs  changelog.41.mfs  changelog.47.mfs  changelog.6.mfs   stats.mfs
[root@mfsmaster1 data]# du -sh
85G	.
[root@mfsmaster1 data]# free -g
             total       used       free     shared    buffers     cached
Mem:            62         62          0          0          3         49
-/+ buffers/cache:          9         53
Swap:            7          0          7
 

the changelog is very big , will this be the reason that  cause  the problem ,  can I delete some changelogs  ?

**Comment by xandrus** [comment]
Removing changelogs will not change anything.
This files are important.

In MooseFS all metadata operations are made in RAM so hdd is not taking part in metadata operations. But in case of metadata file error or some kind of problems, mfsmaster will automatically recover metadata from changelogs.

Can you execute this command and send us reult?
`mfscli -SIG -H mfsmaster.host.name`

By the way. Please check MooseFS master CPU load. What kind of CPU you have?
Please remember that MooseFS master is single thread so CPU clock is very important. When CPU has many threads, power governor is not able to increase CPU clock only for one thread and works on lowest speed.

**Comment by Damien9527** [comment]
Hi,@xandrus 
    here is the information:
  
 cpuinfo :  Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz


+--------------------------------------------------+
|                   Master Info                    |
+-----------------------+--------------------------+
| master version        |                   3.0.85 |
| RAM used              |                  4.7 GiB |
| CPU used              |                   92.85% |
| CPU used (system)     |                   57.82% |
| CPU used (user)       |                   35.03% |
| total space           |                  220 TiB |
| avail space           |                  143 TiB |
| trash space           |                  747 GiB |
| trash files           |                    88902 |
| sustained space       |                   46 GiB |
| sustained files       |                      123 |
| all fs objects        |                  5822263 |
| directories           |                   533712 |
| files                 |                  5287214 |
| chunks                |                  5006647 |
| all chunk copies      |                 14871838 |
| regular chunk copies  |                 14871838 |
| last successful store | Tue May 23 20:00:07 2017 |
| last save duration    |                    ~6.4s |
| last save status      |      Saved in background |
+-----------------------+--------------------------+

+--------------------------------------------------+
|                   Master Info                    |
+-----------------------+--------------------------+
| master version        |                   3.0.85 |
| RAM used              |                  4.7 GiB |
| CPU used              |                   81.42% |
| CPU used (system)     |                   50.60% |
| CPU used (user)       |                   30.83% |
| total space           |                  220 TiB |
| avail space           |                  143 TiB |
| trash space           |                  796 GiB |
| trash files           |                    88259 |
| sustained space       |                   46 GiB |
| sustained files       |                      123 |
| all fs objects        |                  5822658 |
| directories           |                   533860 |
| files                 |                  5287461 |
| chunks                |                  5007546 |
| all chunk copies      |                 14874535 |
| regular chunk copies  |                 14874535 |
| last successful store | Tue May 23 19:00:07 2017 |
| last save duration    |                    ~6.1s |
| last save status      |      Saved in background |
+-----------------------+--------------------------+

+--------------------------------------------------+
|                   Master Info                    |
+-----------------------+--------------------------+
| master version        |                   3.0.85 |
| RAM used              |                  4.7 GiB |
| CPU used              |                   92.85% |
| CPU used (system)     |                   57.82% |
| CPU used (user)       |                   35.03% |
| total space           |                  220 TiB |
| avail space           |                  143 TiB |
| trash space           |                  746 GiB |
| trash files           |                    88437 |
| sustained space       |                   46 GiB |
| sustained files       |                      123 |
| all fs objects        |                  5821810 |
| directories           |                   533715 |
| files                 |                  5286758 |
| chunks                |                  5006202 |
| all chunk copies      |                 14870500 |
| regular chunk copies  |                 14870500 |
| last successful store | Tue May 23 20:00:07 2017 |
| last save duration    |                    ~6.4s |
| last save status      |      Saved in background |
+-----------------------+--------------------------+




top - 20:01:12 up 783 days, 14 min,  1 user,  load average: 0.32, 0.15, 0.04
Tasks: 357 total,   2 running, 354 sleeping,   0 stopped,   1 zombie
Cpu0  :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu1  :  0.0%us,  0.3%sy,  0.0%ni, 99.3%id,  0.3%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu2  :  0.0%us,  0.3%sy,  0.0%ni, 99.7%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu3  :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu4  :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu5  :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu6  :  3.7%us,  3.7%sy,  0.0%ni, 92.3%id,  0.0%wa,  0.0%hi,  0.3%si,  0.0%st
Cpu7  :  0.3%us,  0.0%sy,  0.0%ni, 99.7%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu8  :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu9  : 28.2%us, 35.1%sy,  0.0%ni, 22.2%id,  0.6%wa,  0.0%hi, 13.9%si,  0.0%st
Cpu10 :  0.0%us,  0.3%sy,  0.0%ni, 99.7%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu11 :  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  65932784k total, 64402868k used,  1529916k free,  3729312k buffers
Swap:  8388600k total,     7144k used,  8381456k free, 50813440k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 7027 mfs        1 -19 4881m 4.7g 1320 R 89.2  7.5  73787:06 mfsmaster3

**Comment by marcin-github** [comment]
I saw messages on mfschunkserver when I used mfs in 3.0. 86 . Aleksander, when we talk about issue with kvm on mfs I saw and I mention about such messages. After upgrading to 3.0.88 problem disappeared.

**Comment by oxide94** [comment]
So as I can see, the issue is resolved. Correct?

**Comment by Damien9527** [comment]
@marcin-github   I have also run kvm on another mfs cluster , the mfs version is 3.0.88 , the ETIMEDOUT  error still exist  . the master  information blow:
May 22 20:22:31 localhost mfschunkserver[7808]: connect to 10.39.2.113:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 02:10:06 localhost mfschunkserver[7808]: connect to 10.39.2.113:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 08:56:50 localhost mfschunkserver[7808]: connect to 10.39.2.115:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 09:00:01 localhost mfschunkserver[7808]: connect to 10.39.2.113:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 09:06:39 localhost mfschunkserver[7808]: connect to 10.39.2.115:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 09:07:22 localhost mfschunkserver[7808]: connect to 10.39.2.115:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 09:07:54 localhost mfschunkserver[7808]: connect to 10.39.2.114:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 09:13:35 localhost mfschunkserver[7808]: connect to 10.39.2.114:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 09:16:23 localhost mfschunkserver[7808]: connect to 10.39.2.113:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 09:29:59 localhost mfschunkserver[7808]: connect to 10.39.2.113:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 09:29:59 localhost mfschunkserver[7808]: connect to 10.39.2.113:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 09:30:16 localhost mfschunkserver[7808]: connect to 10.39.2.113:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 09:30:16 localhost mfschunkserver[7808]: connect to 10.39.2.113:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 09:32:37 localhost mfschunkserver[7808]: connect to 10.39.2.112:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 09:46:06 localhost mfschunkserver[7808]: connect to 10.39.2.115:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 09:46:29 localhost mfschunkserver[7808]: connect to 10.39.2.115:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 09:50:00 localhost mfschunkserver[7808]: connect to 10.39.2.113:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 09:54:48 localhost mfschunkserver[7808]: connect to 10.39.2.113:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 09:55:56 localhost mfschunkserver[7808]: connect to 10.39.2.114:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 11:09:32 localhost mfschunkserver[7808]: connect to 10.39.2.114:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 11:33:34 localhost mfschunkserver[7808]: connect to 10.39.2.113:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 12:28:35 localhost mfschunkserver[7808]: connect to 10.39.2.114:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 12:55:57 localhost mfschunkserver[7808]: connect to 10.39.2.112:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 13:06:39 localhost mfschunkserver[7808]: connect to 10.39.2.112:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 20:35:32 localhost mfschunkserver[7808]: connect to 10.39.2.114:9422 failed, error: ETIMEDOUT (Operation timed out)
May 23 23:00:18 localhost mfschunkserver[7808]: connect to 10.39.2.114:9422 failed, error: ETIMEDOUT (Operation timed out)
May 24 02:20:19 localhost mfschunkserver[7808]: connect to 10.39.2.113:9422 failed, error: ETIMEDOUT (Operation timed out)
May 24 03:56:08 localhost mfschunkserver[7808]: connect to 10.39.2.114:9422 failed, error: ETIMEDOUT (Operation timed out)
May 24 05:00:02 localhost mfschunkserver[7808]: connect to 10.39.2.113:9422 failed, error: ETIMEDOUT (Operation timed out)


+--------------------------------------------------+
|                   Master Info                    |
+-----------------------+--------------------------+
| master version        |                   3.0.88 |
| RAM used              |                  613 MiB |
| CPU used              |                    2.06% |
| CPU used (system)     |                    1.18% |
| CPU used (user)       |                    0.88% |
| total space           |                  115 TiB |
| avail space           |                   61 TiB |
| trash space           |                   13 TiB |
| trash files           |                      657 |
| sustained space       |                   59 GiB |
| sustained files       |                        2 |
| all fs objects        |                   149431 |
| directories           |                    12825 |
| files                 |                   136536 |
| chunks                |                   432294 |
| all chunk copies      |                  1177059 |
| regular chunk copies  |                  1177059 |
| last successful store | Wed May 24 09:00:00 2017 |
| last save duration    |                    ~0.3s |
| last save status      |      Saved in background |
+-----------------------+--------------------------+



@oxide94      So  all the problems  are  caused by the heavy load of the  master's cpu  ?

**Comment by xandrus** [comment]
Basically please update MooseFS to latest version 3.0.92.

Your last log shows that all is pointing to some LAN problems.
Can you check if MTU is set correctly in your cluster. I mean on all hosts, and switches?

If you have Jubo Frames try this command:
`ping -M do -s 8972 ip-addres-of-moosefs-component`

**Comment by Damien9527** [comment]
Hi, @xandrus 
   I will update the version later . 


  All  the MTU   of the cluster server is 1500 , I don't change it .     
  Here is one of my  network interface  infomation.   there have dropped and overruns packets  sometimes  .   

          bond0     Link encap:Ethernet  HWaddr 6C:92:BF:37:A9:88
          inet addr:10.39.54.216  Bcast:10.39.54.255  Mask:255.255.255.0
          inet6 addr: fe80::6e92:bfff:fe37:a988/64 Scope:Link
          UP BROADCAST RUNNING MASTER MULTICAST  MTU:1500  Metric:1
          RX packets:272807957677 errors:0 **dropped:841871 overruns:841871** frame:0
          TX packets:238289478692 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:238561113717897 (216.9 TiB)  TX bytes:216139199147157 (196.5 TiB)

**Comment by marcin-github** [comment]
Dropped packets on bond interface in active-backup mode is something expected because one physical interface (slave) is dropping packets. But you have high value of overruns, this is something that needs investigation.

**Comment by xandrus** [comment]
Thank you for all this information.
Number of dropped and overruns packets is really small.

I would like to suggest to execute one test.
Can you run below bash line on chunkserver or chunkservers and log mfsmaster ping log each 30 second. Please run it by two or 3 hours. This test will tell us if master host is responsible all the time. 

`while true ; do d=$(date) ;  p=$(ping -c1 mfsmaster.ct.lan) ; echo ${d} ${p} ; sleep 30 ; done | tee ping-test.log`

Your logs show, that disconnections are happening more or less regularly.
By the way, what kind of filesystem you have on chunkserver disks?

**Comment by xandrus** [comment]
From the other side it is better to use "sleep 1" than "sleep 30".

**Comment by Damien9527** [comment]
HI, @xandrus  

     My disks filesystem  is  ext4 .

  I have run your ping test  on my chunkservers   every 5s  in  last 12 hours  ,  but there  have no packet loss .  
   cat ping-test.log |grep  -v "0% packet loss"

cat ping-test.log|wc -l
10715

I  have collected  master chart data  every half an hour ,  the cpu usage is still up to 100%, and the sys usage is also very high .    sometimes  the master  response error :

mfscli   -H 10.39.2.243   -SMC -b cpu -b scpu -b ucpu -b open -b write

                                        date                         cup          sys       user       open              write 
Master chart data:      2017-05-26 08:49        117.98% 88.66%  29.31%  2662.767/s      863.067/s
Master chart data:      2017-05-26 08:48        118.30% 88.61%  29.70%  2677.900/s      852.267/s
Master chart data:      2017-05-26 08:47        116.39% 87.16%  29.23%  2665.417/s      857.633/s
Master chart data:      2017-05-26 08:46        121.73% 90.97%  30.75%  2723.050/s      850.583/s
Master chart data:      2017-05-26 08:45        119.40% 89.52%  29.87%  2661.150/s      829.400/s
Master chart data:      2017-05-26 08:44        116.04% 87.01%  29.03%  2517.567/s      809.333/s
Master chart data:      2017-05-26 08:43        118.94% 88.95%  30.00%  2463.917/s      802.933/s
Master chart data:      2017-05-26 08:42        116.46% 87.68%  28.79%  2374.767/s      756.600/s
Master chart data:      2017-05-26 08:41        119.40% 88.78%  30.62%  2437.500/s      745.683/s
Master chart data:      2017-05-26 08:40        115.97% 87.33%  28.64%  2398.200/s      733.983/s
Master chart data:      2017-05-26 08:39        116.16% 87.18%  28.98%  2354.583/s      711.750/s
Master chart data:      2017-05-26 08:38        120.29% 89.67%  30.62%  2414.583/s      728.883/s
Master chart data:      2017-05-26 08:37        119.90% 89.61%  30.30%  2445.850/s      778.417/s
Master chart data:      2017-05-26 08:36        121.85% 91.15%  30.70%  2361.183/s      851.550/s
Master chart data:      2017-05-26 08:35        118.26% 88.72%  29.54%  2268.067/s      845.067/s
Master chart data:      2017-05-26 08:34        119.35% 89.13%  30.22%  2379.067/s      802.567/s
Master chart data:      2017-05-26 08:33        122.73% 91.55%  31.19%  2296.350/s      743.667/s
Master chart data:      2017-05-26 08:32        121.77% 91.33%  30.44%  2372.117/s      900.733/s
Master chart data:      2017-05-26 08:31        126.77% 93.65%  33.13%  2446.900/s      785.733/s
Master chart data:      2017-05-26 08:30        121.68% 91.42%  30.26%  2414.333/s      763.267/s
 


Traceback (most recent call last):
  File "/usr/local/moosefs-3.0.92/bin/mfscli", line 7198, in <module>
    if masterconn.version_at_least(2,0,15):
AttributeError: 'NoneType' object has no attribute 'version_at_least'
-------------------------------------------------------------------------------------------------------------------


ip	                version	state	metadata version	RAM used	CPU used ▼
10.39.0.248	3.0.85	-	      30 398 693 322	       4.8 GiB	all:118.54% sys:88.86% user:29.69%

**Comment by xandrus** [comment]
Hi.
Thank you for all this information.
First of all I would like to add, that we have fixed this traceback issue.

According to high CPU usage. In your case it looks like your power management is not able to increase cpu speed for one core. As we mentioned before MooseFS Master is single thread. When MooseFS master process uses 100% of single thread, power governor will not increase speed because all other 11 CPU treads doing nothing. 

Would you be so kind and disable power governor on MooseFS master server(for test only)?
Please check if CPU usage dropped?

`echo performance | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor >/dev/null`

Please also read this article about CPU speed and number of cores for MooseFS master server.
[https://moosefs.com/documentation/best-practices.html#hardware](https://moosefs.com/documentation/best-practices.html#hardware)

**Comment by xandrus** [comment]
One more request.
Can you check dmesg on your chunkservers?
Maybe it will tell us something more.

**Comment by Damien9527** [comment]
Hi,
     I have check the  cpufreq items .  sometimes  the  file disappeard.    I can't change the content in it .
    /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor 

    We try to bulid another mfscluster to replace this  problem one .




   the dmesg on chunkservers didn't seem have any error .  

one of  the demsg:

bonding: MII link monitoring set to 1 ms
Loading kernel module for a network device with CAP_SYS_MODULE (deprecated).  Use CAP_NET_ADMIN and alias netdev-bond0 instead
ADDRCONF(NETDEV_UP): bond0: link is not ready
8021q: adding VLAN 0 to HW filter on device bond0
bonding: unable to remove non-existent slave eth0 for bond bond0.
bonding: bond0: Adding slave eth0.
8021q: adding VLAN 0 to HW filter on device eth0
bonding: bond0: enslaving eth0 as an active interface with a down link.
bonding: bond0: Adding slave eth1.
8021q: adding VLAN 0 to HW filter on device eth1
bonding: bond0: enslaving eth1 as an active interface with a down link.
ADDRCONF(NETDEV_UP): bond0: link is not ready
8021q: adding VLAN 0 to HW filter on device bond0
bonding: bond0: Removing slave eth1
bonding: bond0: releasing active interface eth1
bonding: bond0: Adding slave eth1.
8021q: adding VLAN 0 to HW filter on device eth1
bonding: bond0: enslaving eth1 as an active interface with a down link.
igb: eth0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: None
bond0: link status definitely up for interface eth0, 1000 Mbps full duplex.
ADDRCONF(NETDEV_CHANGE): bond0: link becomes ready
bond0: no IPv6 routers present
EXT4-fs (sda6): mounted filesystem with ordered data mode. Opts:
igb: eth1 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: None
bond0: link status definitely up for interface eth1, 1000 Mbps full duplex.
fuse init (API version 7.13)

**Comment by Damien9527** [comment]
Hi   @xandrus 
      We have find out that  there have  thousand projects do the svn checkout every day , Almost  3000/s  open  operations  and  1000/s  write operations. these operations make the mfsmaster cpu load heavy . every day there have more than thousand 'ETIMEOUT' errors  in all chunkservers, and  some also some  'masterconn: connection timed out' error in hourly.

    I  change the  svn checkout frequency . than  the open and write  operations drop to   1500/s  and 500/s  .   the 'ETIMEOUT' errors less than 100. but the 'masterconn: connection timed out' still appeared sometimes.   the mfsmaster load seems didn't degrade.

--------------------------------------------------------------
mfscli   -H 10.39.2.243     -SMC -b cpu -b scpu -b ucpu -b open -b write
Master chart data:      2017-05-25 12:01        128.94% 94.78%  34.16%  3033.383/s      1590.417/s
Master chart data:      2017-05-25 12:00        119.28% 91.46%  27.82%  2451.617/s      1376.700/s
Master chart data:      2017-05-25 11:59        119.28% 88.70%  30.57%  3054.317/s      1688.133/s
Master chart data:      2017-05-25 11:58        121.45% 89.99%  31.46%  3040.017/s      1744.150/s
Master chart data:      2017-05-25 12:32        129.03% 95.27%  33.76%  2936.333/s      1235.517/s
Master chart data:      2017-05-25 12:31        132.03% 96.52%  35.52%  2883.100/s      1180.300/s
Master chart data:      2017-05-25 12:30        119.92% 89.72%  30.19%  2908.767/s      1219.850/s
Master chart data:      2017-05-25 12:29        118.40% 88.88%  29.52%  2911.883/s      1194.800/s
Master chart data:      2017-05-25 12:28        120.46% 90.48%  29.97%  2942.183/s      1193.083/s
Master chart data:      2017-05-25 12:27        120.59% 90.36%  30.23%  2995.767/s      1134.883/s
Master chart data:      2017-05-25 12:26        122.65% 91.72%  30.93%  2992.217/s      1088.083/s
Master chart data:      2017-05-25 12:25        119.97% 90.13%  29.84%  2939.117/s      1090.733/s
Master chart data:      2017-05-25 12:24        118.22% 89.17%  29.05%  2897.967/s      1184.267/s
         

Master chart data:      2017-06-01 08:41        123.52% 90.44%  33.07%  1290.567/s      881.533/s
Master chart data:      2017-06-01 08:40        127.31% 93.16%  34.15%  1279.083/s      967.183/s
Master chart data:      2017-06-01 08:39        120.71% 88.35%  32.36%  1226.633/s      775.017/s
Master chart data:      2017-06-01 08:38        119.66% 87.83%  31.84%  1206.533/s      693.600/s
Master chart data:      2017-06-01 08:37        124.96% 91.17%  33.80%  1225.050/s      696.900/s
Master chart data:      2017-06-01 08:36        125.24% 91.29%  33.94%  1135.717/s      647.300/s
Master chart data:      2017-06-01 08:35        126.85% 92.56%  34.29%  1169.617/s      628.333/s

**Comment by xandrus** [comment]
Thank you for this information.
Right now we are in progress of MooseFS chunkserver investigation. Maybe we will find the real source of problem.
We also suspect that unlink operation on XFS filesystem can influence on chunkserver timeouts but we have to gather more information according this topic.

We are in touch. 
If we find something interesting we will inform you.

**Comment by Damien9527** [comment]
That's very kind of you .  Thank you very much for your advises  . 

Wait for your good news .

**Comment by chogata** [comment]
Closing this topic, since it's two years old and concerns an outdated version of MooseFS.
